### ISSUE TITLE
Change colour scheme and logos

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/afrosolouk#3]

**Comment by oluoluoxenfree** [comment]
[logosforafrosolo.zip](https://github.com/geeksforsocialchange/afrosolouk/files/13928125/logosforafrosolo.zip)

logos for sponsors (possibly all already in the site tbh, many of the sponsors overlap)

**Comment by oluoluoxenfree** [comment]
[asuksupportdocumentstext.zip](https://github.com/geeksforsocialchange/afrosolouk/files/13928138/asuksupportdocumentstext.zip)

text and images to go with sponsor info i think

**Comment by oluoluoxenfree** [comment]
need favicons, and pngs for the apple and android specific images if still relevant. also these: mstile-150x150.png
og_1-1.png
og_2-1.png

**Comment by katjam** [comment]
@oluoluoxenfree I believe this has been completed. If so, can you link to the Pull Request(s) and close?
