### ISSUE TITLE
Replace project participants

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/afrosolouk#4]
- [x] Section called "Life stories"
- [x] Add all participant information
- [x] Choose one photo
- [ ] #11
- [x] Remove Avari from the Life stories section (he should remain in the collection, but not be featured in the website as per email request)

### Omitted
- Eric Skilton because he did not have a photo
- Burjor Avari by request of SuAndi

**Comment by oluoluoxenfree** [comment]
https://www.dropbox.com/scl/fo/6b6a7wut3mnm4nlalfru0/h?rlkey=0kiw01yh77hjzgbox4o9182vh&dl=0

**Comment by oluoluoxenfree** [comment]
@katjam the extracts and full names for each participant are hopefully all on the Wayback Machine: https://web.archive.org/web/20210625095116/http://afrosolouk.com/stories
