### ISSUE TITLE
Swap SOM book with ASUK book

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/afrosolouk#5]

**Comment by oluoluoxenfree** [comment]
https://www.dropbox.com/scl/fi/qm5096s2j1x3t248dr897/Afro-Solo-Site-download.pdf?rlkey=zd28oj5ujemydc9r9a3ljarb1&dl=0

**Comment by oluoluoxenfree** [comment]
I removed the book section (save for the quote) in one of the PRs i raised today, can put that section back if you would like to ask suandi about it as well. @katjam

**Comment by kimadactyl** [comment]
I imagine the book will want to be there? Or are you thinking of using a new provider?

**Comment by oluoluoxenfree** [comment]
I was mostly comparing to the old site which just linked straight to the
PDF? but i don't know if this way makes more sense, to upload to scribd or
something similar.

**Comment by kimadactyl** [comment]
I think it makes sense to just set it up exactly as it is on https://ourmothers.org/ :) gives option for both download or view in scribd?

**Comment by katjam** [comment]
@oluoluoxenfree I believe this has been completed. If so, please close. If not, make a note here about what work still needs doing.
